image:
- Visual Studio 2022
build: off
init:
- sh: curl -sflL https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh | bash -e -
install:
- ps: docker run mcr.microsoft.com/windows:1809 cmd /k "echo hello"
