image:
- Visual Studio 2022
build: off
init:
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
- ps: |
    &$Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchWindowsEngine
install:
- ps: docker run mcr.microsoft.com/windows/servercore:ltsc2019 cmd /k "echo hello"
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
